### ISSUE TITLE
Wagtail 3.0 compatibility?

### ISSUE THREAD

**Issue by djch** [ephes/wagtail_srcset#2]
It seems that I get a failure of dependency resolution trying to update to Wagtail 3.0 with wagtail_srcset in my Pipfile. For all I know this project is still compatible, but perhaps there's a dependency locking it to Wagtail 2.x somewhere in this project?

**Comment by ephes** [comment]
Ups, didn't notice this issue. You are right, in the `pyproject.toml` there's an implicit upper limit to Wagtail 2: `wagtail = "^2.8"`.  Here's a [video describing the problem in detail](https://youtu.be/Gr9o8MW_pb0).

Maybe I find time this week to switch from poetry to flit for building the package and remove the upper version limits.

**Comment by djch** [comment]
Thanks!

Not really related to this issue, but apparently Wagtail are working on some kind of first-party support for srcset images as well: [https://github.com/wagtail/rfcs/pull/71](https://github.com/wagtail/rfcs/pull/71)

**Comment by ephes** [comment]
Yes, I saw this too and this would be really great if there's a proper solution for this. But it seems a little bit strange to me that the [rfc](https://github.com/wagtail/rfcs/blob/main/text/071-responsive-images-support.md) is mainly talking about traffic reduction. The only reason I built [wagtail_srcset](https://github.com/ephes/wagtail_srcset) was because my fotos looked awful on a standard Wagtail installation.

Reducing traffic is an also important, but completely different problem. The easiest way to accomplish that would be to look into using different quality settings for different images using something like [cjpeg-dssim](https://github.com/technopagan/cjpeg-dssim) (there's a lot more to this problem, of course - especially if you take into account different compression formats like webp etc.. but for jpeg it's already complicated enough). But maybe there's also some lack of understanding on my site..
